### ISSUE TITLE
Please consider a template with Vite support

### ISSUE THREAD

**Issue by ameyer117** [mcansh/remix-fastify#179]
Hello @mcansh & thank you for creating this project, its been a blessing for me.

I'd humbly like to request that you _consider_ creating a template for vite support as well based on the express template -> https://github.com/remix-run/remix/tree/main/templates/unstable-vite-express

Thank you!

**Comment by mcansh** [comment]
😬 https://github.com/mcansh/remix-fastify/tree/main/examples/unstable-vite

**Comment by ameyer117** [comment]
Awesome news! Thank you! 🚀

**Comment by ameyer117** [comment]
It appears looks like vite is an option & documentated now. 🎉

**Comment by mcansh** [comment]
@ameyer117 looks like i forgot to update the dev/build scripts in the vite template, if you already created an app, go ahead and update those https://github.com/mcansh/remix-fastify/commit/9b3a0212a4472b658498dbf180372c47f5d51d1e

and i also fixed the FOUC issue on initial page loads #184 which is a template change

**Comment by ameyer117** [comment]
I'll spin up a new version of the template and copy my code over. Thanks again!

**Comment by ameyer117** [comment]
@mcansh - Just wanted to report in that everything works perfectly, including the `3.2.0-pre.0` version! I dont' see any FOUC issues at all. 🚀

**Comment by mcansh** [comment]
🥳 wonderful! doing a couple of deep imports from the `@remix-run/dev` package but hopefully those can go away once the vite plugin gets closer to stable and provides another way to get the critical css

**Comment by ameyer117** [comment]
All good, much better than the alternative of using express. (Which I still can't believe hasn't received any security updates in over a year).
